### ISSUE TITLE
Is it spossible to have Default Dev-Space point to custom host name and use SSL?

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#109]
Is it possible to use Dev-Spaces with a custom host name and SSL?

We have a scenario where we want to move a SF appliation into AKS and use Dev-Spaces, but we have failed to find any information about how to setup the public endpoints to use SSL and custom host name.

Our site authenticate it's users using OAUTH2 provided by Identity Server 4 running as a custom public site. After the user has logged in, he/she gets redirected to the main site.

We would like to use SSL in our development scenario so we don't expose any test credentials unencrypted and to make sure that HTTP wont work in production.

**Comment by stepro** [comment]
Theoretically it should be possible to utilize your own custom ingress controller with SSL etc., but the team has not tested the scenario. There is one prerequisite for your own ingress controller, which is that it is able to automatically respond to ingress objects in the cluster and update DNS records as necessary to enable all the defined host names. This ensures that for each ingress object you define, variation host names such as "myspace.s.yourdomain.com" will also work and perform routing correctly.

The other change you will need to make is in your azds.yaml for your public services. By default, we configure any ingress objects installed by the default Helm charts we produce to include the annotation `kubernetes.io/ingress.class: traefik-azds`. You will want to change this so that the ingress object is picked up by your custom ingress controller instead.

If you plan to try this out, I'd be happy to help you troubleshoot. Let me know how it goes :)

**Comment by Eneuman** [comment]
Thank you for the information. I will try to setup my solution using http at first before I endevor into the SSL jungle.

**Comment by saradotramli** [comment]
Using the default ingress controller that azds uses (traefik), is it possible to enable https access for an ingress?

**Comment by thargy** [comment]
I've been scratching my head for a couple of days now trying to get a simple ASP.NET Core 3 blank project authenticating via AzureAD.  AzureAD requires an HTTPS endpoint for authentication flow, and won't let you configure an HTTP endpoint for login redirection.

Setting up a new Dev Space in VS2019 is really nice, except there's no easy way to enable SSL.  All the online documents assume you set up your own cluster and go into loads of detail, but not of that maps easily on to the supplied config files.  Traefik does apparently support SSL, so I guess it's possible, and the template yaml includes some commented-out lines for `tls` and a toggle for `kubernetes.io/tls-acme` both of which suggest that it should be possible.  But figuring out how to configure it has defeated me.

Is there a walkthrough anywhere for configuring a public HTTPS endpoint (SSL/TLS) on a Dev Space, or even just an example? Without it, Dev Spaces are unusable for testing sites that require AzureAD authentication?

Thanks

**Comment by thargy** [comment]
I've [added an issue to the relevant docs](https://github.com/MicrosoftDocs/azure-docs/issues/36353) too.

**Comment by saradotramli** [comment]
I was able to follow these instructions to achieve this eventually:
https://docs.microsoft.com/en-us/azure/aks/ingress-tls
 As @stepro pointed out, the key is to swap out the ingress class in the azds.yaml and match it to the documentation.

**Comment by thargy** [comment]
Thanks @saradotramli, I had seen that doc but it was a step too far for me, when what I wanted was to get to coding.

In the end enabling Remote Debugging on an App Service was significantly easier to achieve, and less expensive in Azure Credits.  Spending >£10 of credit to get nowhere with Dev Spaces rules it out for me when the point is to be able to quickly and conveniently get the environment set up and working so you can get to developing code not configuring infrastructure.

For my use case (developing a new site with AzureAD integration) the time investment required was unjustified.  It would he interesting to know your use case, as I’m constantly evaluating new solutions?  I haven’t started evaluating the team working benefits.

**Comment by zr-msft** [comment]
This was just recently published, which seems to cover the initial question posed by @Eneuman :

https://docs.microsoft.com/azure/dev-spaces/how-to/ingress-https-traefik
