### ISSUE TITLE
[Guidance] - on Adding a Sql Server into the fold..

### ISSUE THREAD

**Issue by dazinator** [Azure/dev-spaces#111]
I have a simple asp.net core web application in my solution.
Thanks to guidance offered on #106, when I run it in Dev Spaces, it now has persistent storage attached and the app works (yippee)

The next part of my trial of dev spaces is to see if I can also get a sql server developer edition deployed to the dev space when I run the web application..

Having stared at these helm yaml files in my project more (I still don't fully understand it!) it looks as though I should be able to find a `helm chart` for a sql server developer edition instance. Suppose I do find one, how do I make it so that when i hit f5 in VS, the deployment to Dev Spaces will deploy not only my current helm crat for my web application, but also this new one that I am hoping I can find on the interwebs?

Side note: I found this https://github.com/helm/charts/tree/master/stable/mssql-linux which looks like it can be installed with a simple command. Can I run this command during my dev space deployment or do I have to copy the chart source files into my project?

Thanks

**Comment by daniv-msft** [comment]
Thank you for contacting us. You might want to have a look at our BikeSharingApp sample that uses a SQL database: https://github.com/Azure/dev-spaces/tree/master/samples/BikeSharingApp/Databases/charts/databases

In this sample, we're actually using the same SQL Docker image as the one you mention (microsoft/mssql-server-linux).

Unfortunately, we don't have in the sample a deployment scenario as straightforward as just hitting F5 to redeploy the whole database. In the sample it works in two-steps:
1. Deploy the database through a simple Helm install.
2. Deploy a separate service (Users in the case of the sample) that takes care of creating the DB's Users table. Here is the code where this happens if you want to have a look: https://github.com/Azure/dev-spaces/blob/master/samples/BikeSharingApp/Users/server.js

**Comment by dazinator** [comment]
Interesting, I will take a further look at that project.

I understand that the router that dev spaces provides, will only re-route http traffic to the parent space if not resolved from the current space. Does this mean if I have a sql server node in the default space, but my web app is spun up in a child space, if it tries to connect to the sql server service, it wont be able too because the sql connection / traffic wont be forwarded / re-routed to the sql instance on parent / default space? Therefore if a service uses sql server, then sql server must always be present in the same space?

**Comment by stepro** [comment]
@dazinator, regarding your first question (hit F5 and everything deploys), you might find that it works to add the SQL Helm chart as a dependency in your service's Helm chart. I believe dev spaces recognizes when a dependency exists and it makes sure those are also installed.

On the second question, if you were to spin up a SQL server in a parent space, a service in the child space will be able to route to it without any special work on your end (this is done through some simple DNS fallback rules in resolv.conf). If you were to spin up the SQL server in the same child space, your service would start routing to that one instead.

The scenario that will *not* work is if you want a service in a parent space to route to a SQL server in a child space. This is because parent->child routing depends on the `azds-route-as` HTTP header to gather the appropriate context regarding where to go, but that information is only available on HTTP requests, not on other protocols such as TDS.

**Comment by dazinator** [comment]
@stepro understood - thanks. I'll try this out.
