### ISSUE TITLE
[Question] Is there an expression variable for just the name of the space?

### ISSUE THREAD

**Issue by markphillips100** [Azure/dev-spaces#112]
I need to pass the name of the space being used into my project's chart.  I was hoping there was something like $(space) that just supplies the name, unlike $(spacePrefix) which appends the ".s.".

Is there an expression variable that can supply me just the name of the space?  Also, is there a documented list of all the expression variables available?

**Comment by markphillips100** [comment]
Just to add, for now I am using ```{{ .Release.Namespace }}``` in a (configmap) template.  The template is very much like the secrets.yaml in that it's rendered content is determined by the values data, hence the reason I'd prefer being able to "set" the namespace via a value property rather than embedded in the template.

**Comment by stepro** [comment]
The best way to do this is to use what Kubernetes calls the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/). In short, add something like this to your pod definition in deployment.yaml:

```
env:
...
- name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
...
```

If you need to know the namespace for some other reason, `{{.Release.Namespace}}` is a reasonable value to use. It doesn't really make sense for this to be in values.yaml or passed in by azds.yaml because the namespace is already set as part of the ambient context (dev space == namespace, and there's always a currently selected dev space you are working in).

The set of expression variables in azds.yaml is very limited. I don't believe there are any more than $(spacePrefix) and $(hostSuffix). This feature was added specifically to enable parameterization of the host name in an ingress rule that otherwise has to be supplied manually.

**Comment by markphillips100** [comment]
Thanks for the info @stepro.  I'm okay with using the ```{{.Release.Namespace}}``` in a template for now.  I was just curious if it was possible for me to keep my configmap template "clean" so it was mostly a copy/paste for other projects that wanted a configmap.

Just for added clarity I'll explain it in a little more detail.

I used to just fill my configMap.yaml with data statements of the format ```<env-var-name>: {{ .Values.<some-values-property> }}``` but then I spotted the secrets.yaml approach in dev-spaces and thought I'd give that method a shot, like so:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "myproject.fullname" . }}
data:
  Kubernetes__KubeNamespace: {{ .Release.Namespace }}
  {{- range $key, $value := .Values.configMaps }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
```
The "Kubernetes__KubeNamespace" environment variable is just a dependency of some .NET code that needs to know the namespace the process is running in.  It's this variable I would have liked to have had outside of the template.

I know I can't use templating functions in values.yaml files so using {{ .Release.Namespace }} there is a no-go, hence the question if I could have used ```$(space)```.

It's not so much of a problem really, as this namespace value is really only relevant to this specific project I'm working on - as it calls the Kubernetes API.
