### ISSUE TITLE
Official reference document for azds.yaml

### ISSUE THREAD

**Issue by PingPongSet** [Azure/dev-spaces#131]
Is there official reference document for azds.yaml, like below?

https://github.com/Azure/dev-spaces/blob/master/samples/BikeSharingApp/BikeSharingWeb/azds.yaml

**Comment by stepro** [comment]
There is a pretty complete reference buried in [this](https://docs.microsoft.com/en-us/azure/dev-spaces/how-dev-spaces-works#how-running-your-code-is-configured) documentation.

**Comment by PingPongSet** [comment]
I knew that link, but it is more like an informal page.

**Comment by stepro** [comment]
We don't currently have a reference section in the documentation that describes the schema for azds.yaml in a more traditional format. Let us know if you feel there is something missing from the link I sent and we can work to include the information you would like to know.

**Comment by PingPongSet** [comment]
The script on file azds.yaml is not Helm, not K8ts, it is AZDS's own script?

**Comment by stepro** [comment]
The azds.yaml file is a Dev Spaces defined schema that enables a dev experience by defining information that drives Helm and Kubernetes. It is not itself a Kubernetes object spec.

**Comment by iMoses** [comment]
@stepro I'm not sure if the URL you provided used to point to some useful information, but it currently doesn't
It's really a shame that you don't have a basic schema reference, even in the same manner that most helm chart do by simply providing a complete configuration yaml with lots of comments on each part.
At this point i'm not even sure if dev-spaces is right for me because I have no idea how to define and use my already existing helm deployment :\
Personally I think this issue should've remained open. It's been more than a year are basic docs are still an issue..

**Comment by stepro** [comment]
@iMoses, apologies regarding the documentation. Since this issue was opened, the documentation was refactored and the details on each property in azds.yaml have moved [here](https://docs.microsoft.com/en-us/azure/dev-spaces/how-dev-spaces-works-up#how-running-your-code-is-configured). While the documentation doesn't follow a standard reference format for describing the contents of the file, it does contain individual paragraphs that describe each specific property in the file, so I think you will find all the information is there.

This said, we have observed that it can be challenging to get an existing Helm chart working with Dev Spaces even when the contents of this file are understood. If you are having specific issues, please feel free to open an issue on that and we'll do our best to help out.

Alternatively, we have introduced a new approach called Local Process with Kubernetes that you may want to check out. This approach runs your code locally with access to everything running in the cluster, and sidesteps the need to configure your existing Helm chart for deployment first. See some introductory documentation [here](https://docs.microsoft.com/en-us/visualstudio/containers/local-process-kubernetes?view=vs-2019).
