### ISSUE TITLE
Projects dependency configuration file generation via Helm

### ISSUE THREAD

**Issue by PingPongSet** [Azure/dev-spaces#132]
The projects below seems using Helm to define projects dependency on file `requirements.yaml` below,  and azds.yaml and Chart project for each project.

https://github.com/Azure/dev-spaces/blob/master/samples/BikeSharingApp/charts/requirements.yaml
https://github.com/Azure/dev-spaces/tree/master/samples/BikeSharingApp/charts

My questions are:
1 Is my understanding above correct?

2 Is the whole folder, `charts`, above generated manually or via tool?

https://helm.sh/docs/developing_charts/
https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-team-development

**Comment by daniv-msft** [comment]
Thanks for reaching out to us.

1. Yes, your understanding is correct. The "charts" folder you linked above defines in `requirements.yaml` all the services we need to install to get the Bike Sharing sample to work. That way, it is possible to install all services in one helm command, rather than having to install each of them independently.
As you pointed out, each of these services has still its own charts folder.

2. The charts folders we use in our samples are usually generated by Azure Dev Spaces, through `azds prep` command. For context, this generates a chart similar to the one that would be generated by Helm itself through `helm create`.
In the specific case of the dependencies charts folder you linked above, it was created manually because being quite specific to this sample.

**Comment by PingPongSet** [comment]
Great, thanks.

That is what I am thinking, and the opening post was to confirm that.

I am new to kebernetes and Helm.

How to define Helm yaml that

**Comment by daniv-msft** [comment]
Q1
Helm has a different purpose than Azure Dev Spaces, so it's hard to compare Helm alone to Azure Dev Spaces using Helm. As of today Dev Spaces has a dependency on Helm, but that's something that _might_ change in the future. 

Q2
I don't have much more to mention here compared to what was mentioned in https://github.com/MicrosoftDocs/azure-docs/issues/34889.

Q3
If you want to understand Helm charts (and thus better understand the files generated by Dev Spaces), yes https://helm.sh/docs/developing_charts/#charts is a good resource. However, please note that depending of what you plan to do on Azure Dev Spaces, you might not need to update the Helm charts we generate by default through `azds prep` command.

**Comment by PingPongSet** [comment]
> Q3
> If you want to understand Helm charts (and thus better understand the files generated by Dev Spaces), yes https://helm.sh/docs/developing_charts/#charts is a good resource. However, please note that depending of what you plan to do on Azure Dev Spaces, you might not need to update the Helm charts we generate by default through azds prep command.

It is true that Helm charts can be generated by azds prep command for a project. However, for project dependency, charts files have to create manually. Thus, I guess I need to understand all related features of Helm.  Ideally, I only want to learn the minimum for dependency. However, I might have to learn more to know what is minimum :<.
