### ISSUE TITLE
vscode extension - 'Prepare configuration files for Azure Dev Spaces' fails with TypeError

### ISSUE THREAD

**Issue by omencat** [Azure/dev-spaces#164]
Following the nodejs getting-started, I have a working dev spaces with the azds CLI, but the vscode dev spaces extension (MacOS) appears to return an TypeError: Cannot read property 'identifier' of undefined.

I tried deleting the .vscode directory and uninstall reinstall the extension, but the result is the same.

In the meantime, could I view a sample generated launch.json? Or does the extension do more than that, and I need to resolve this issue?

**Comment by daniv-msft** [comment]
Thank you for reporting this issue, and sorry you encounter this bug.
I tried running the NodeJS quickstart and didn't reproduce the issue, but I'm not running on MacOS so I'll try this early next week.
In order to help me investigate, could you please let me know when this error happens? When you trigger the "Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces" command?
Also, could you please confirm that you're running the latest version of the extension (no "Update" shown in the Extensions panel)?

**Comment by daniv-msft** [comment]
Also, having a sample launch.json wouldn't help much if the rest of the extension isn't functional.

If you want to have a look at AZDS in the meantime, I'd suggest using the CLI commands instead ("azds prep --public" to prepare your service, then "azds up" to run it).

**Comment by omencat** [comment]
> In order to help me investigate, could you please let me know when this error happens? When you trigger the "Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces" command?
> Also, could you please confirm that you're running the latest version of the extension (no "Update" shown in the Extensions panel)?

Correct, the error happens when I click on command pallet > Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces. Then I receive an error toast in the lower right corner.

I have confirmed the extension is the latest (no update)

azds prep --public , azds up works as expected, but I do not have the debug configuration in .vscode as expected.

**Comment by daniv-msft** [comment]
Thanks for the information. Now that you ran "azds prep --public" successfully, it is possible that closing and reopening VS Code might be sufficient to create the .vscode folder (a message similar to "Some assets are missing to run and debug in Azure Dev Spaces. Do you want to add them?" will appear if it is the case).

In parallel I'm having a look at this bug and will update this issue once I have something to share.

**Comment by omencat** [comment]
I'm afraid closing and reopening vscode had no change in result when trying to run the prepare config action. Error remains.

**Comment by daniv-msft** [comment]
Alright, thanks for giving it a try. I'll let you know once I have an update on this or have another question.

**Comment by daniv-msft** [comment]
I've made progress in my investigation, and I think I understand why this issue happens.

When you trigger the "Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces" command in a Node.js project, we read the `package.json` file to get the main script to call (the definition looks like `"main": "server.js"`).
If we cannot find this definition, then we'll look for local Javascript files that are often used as entrypoints ("server.js", "app.js", "index.js").
In the case where this also fails and we don't find any local files matching, then we have an error that ultimately shows as a modal:
`Failed to configure 'XYZ' for Azure Dev Spaces with error: TypeError: Cannot read property 'identifier' of undefined`

@omencat > Does this look similar to the Node.js project you're using in this case?
We're pushing a fix for this and we'll release it tomorrow. I'll comment on this issue once the fix is released.

As a side note, we released a new version of the extension today that doesn't fix this but handles the error differently: in this specific case, with the latest available version of the extension, this error wouldn't display any modal.

**Comment by omencat** [comment]
Yeah I dont have a main in my package file, but it doesnt seem to matter if I add it to either the src/main.ts entry or the dist/main.js

Here are the start scripts in my package.json file...
 
```
    "start": "ts-node -r tsconfig-paths/register src/main.ts",
    "start:dev": "tsc-watch -p tsconfig.build.json --onSuccess \"node dist/main.js\"",
    "start:debug": "tsc-watch -p tsconfig.build.json --onSuccess \"node --inspect-brk dist/main.js\"",
    "start:prod": "node dist/main.js",
```

**Comment by daniv-msft** [comment]
The new version of the extension including the fix I mentioned above has been released.

> Yeah I dont have a main in my package file, but it doesnt seem to matter if I add it, and point it to either the src/main.ts entry or the dist/main.js

Unfortunately, given that we run the language detection logic only once when your open a folder, if you just kept the same folder opened in VS Code, made some changes in the package.json and ran the "Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces" command, your package.json changes weren't reevaluated.

Could you please give a try to the new version of the extension?
* If you already have an "azds.yaml" file in your workspace folder, then you should see a modal:
"[Azure Dev Spaces] Required assets to build and debug in Azure Dev Spaces are missing from 'XYZ'. Add them?"
Clicking "Yes" will create the .vscode folder.
* If you don't have an "azds.yaml" file, you'll have to run the "Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces" command, which will also create the .vscode folder.

Please note though that, if we weren't able to find the "main" defined in package.json, nor a matching entrypoint in your files, we will default the `.vscode/launch.json` and `.vscode/tasks.json` to using "server.js". Depending of what you use locally, you'll need to change this.

**Comment by omencat** [comment]
Hi Daniv,

I just wanted to let you know that after restarting vscode and installing the latest update, new configs have been added to launch.json.. We have made some breaking changes for this weekend so I will let you know the result in a few days, but for now things look promising with respect to the extension!

**Comment by daniv-msft** [comment]
Great, thanks @omencat for confirming that the .vscode folder is created with the latest version of the extension!
Yes, please let us know if you encounter any other issues with the extension.

**Comment by omencat** [comment]
Thanks for the quick resolution @daniv-msft
