### ISSUE TITLE
node.js not restart after updating server.js

### ISSUE THREAD

**Issue by doggy8088** [Azure/dev-spaces#167]
I'm use Windows 10 (v10.0.18362.356). Here are the steps to reproduce this problem:

1. Prepare AKS and Dev Spaces

2. Prepare the code for running on Azure Dev Spaces

    ```sh
    git clone https://github.com/Azure/dev-spaces.git
    cd dev-spaces\samples\nodejs\getting-started\webfrontend
    azds prep --public
    ```

3. Run the code

    ```sh
    azds up
    ```

4. Test the running app

5. Modify `server.js` file and **Save** (The updated file will upload to the workload automatically)

    Just simply change the `Hello from webfrontend` into `Hello from other`.

I expected the `node` should restart, but it doesn't.

**Comment by philon-msft** [comment]
Hi @doggy8088, to get node to restart automatically, nodemon will need to be running. The easiest way to do that is by running your code using the 'Attach to server (AZDS)' debug mode in the Dev Spaces extension for VS Code rather than `azds up`. 

These docs should help explain:
https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-nodejs#update-code-from-visual-studio-code
https://docs.microsoft.com/en-us/azure/dev-spaces/get-started-nodejs#debug-a-container-in-kubernetes
