### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by RyanHill-MSFT** [Azure/dev-spaces#260]
- Issue Type: `Performance`
- Extension Name: `azds`
- Extension Version: `2.0.220191204`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.41.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ryhill\azuredevspaces.azds-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[azuredevspaces.azds-unresponsive.cpuprofile.txt](https://github.com/Azure/dev-spaces/files/3996261/azuredevspaces.azds-unresponsive.cpuprofile.txt)

**Comment by daniv-msft** [comment]
Thank you Ryan for reporting this issue! At first sight this seems to be due to file system calls.
I was quite sure that we switched all of them to asynchronous calls a few months ago, but we must have missed one.

I'm having a look at this to determine when the issue happens, and I'll let you know as soon as I have something to share.

**Comment by daniv-msft** [comment]
According to my investigation, this issue is due to multiple things:
- We were still doing indirectly some of our file system operations synchronously.
- We are not bundling properly our extension, which results in the separate loading of a lot of small files rather than a couple of big ones.

The fix for these will be deployed with the next release of the extension, at the beginning of January. I'll close this issue once the fix is released.

**Comment by daniv-msft** [comment]
The new version of the VS Code extension including this fix was released today!
I'm closing this issue, but please let us know if you run into any other problem.
