### ISSUE TITLE
Azure Dev Spaces CLI not working inside VS Code Dev Container with .NET Core 3.0 or 3.1

### ISSUE THREAD

**Issue by drivexcite** [Azure/dev-spaces#263]
**Describe the bug**
This bug occurs after setting up a development environment with the Azure CLI, Kubectl, and Azure Dev Spaces CLI inside a Visual Studio Code Dev Container.

**To Reproduce**

1. Open a Powershell Console.
2. Create a new folder called DevSpacesRemoteContainer. 

`mkdir DevSpacesRemoteContainer`
`cd DevSpacesRemoteContainer`

3. Create a Visual Studio Code Remote Container directory.

`mkdir .devcontainer`

4. Copy the attached files (`devcontainer.json` & `Dockerfile`) inside the `.devcontainer` directory.
5. Open an instance of Visual Studio Code `code .`
6. Install the Remote Containers extension.
7. Press Ctrl + Shift + P and select "Remote-Containers:Reopen in Container".
8. After the container gets created, open a new Terminal in VS Code, by pressing Ctrl + Shift + `.
9. Enter in the terminal the following command and press Enter:
`azds prep --public`

**Actual behavior**
The command aborts execution with an error message indicating a missing dependency, despite the fact that there is a version of OpenSSL installed in the container already.
```bash
root@5587249543ce:/workspaces/DevSpacesRemoteContainer# azds prep --public
No usable version of the libssl was found
Aborted
```
To verify the existence of a current version of LibSSL:
`ldconfig -p|grep ssl`

 
**Expected behavior**
The command creates a Helm Chart, a Dockerfile and an Azure Dev Spaces YAML file, as described in the documentation.
 
**Environment Details**
Client used (CLI/VS Code/Visual Studio):
Azure CLI: 2.0.78
Azure Dev Spaces CLI Version: 1.0.20191212.6
Operating System: Debian 9 (container image based on mcr.microsoft.com/dotnet/core/sdk:3.0)
 
**Additional context**
This problem also exists in .NET Core 3.1. To reproduce that, change the first line in `Dockerfile` to:
`ARG DOTNETCORE_VERSION=3.1`

It will work just fine if changed for .NET Core 2.2:
`ARG DOTNETCORE_VERSION=2.2`

[DevSpacesRemoteContainer.zip](https://github.com/Azure/dev-spaces/files/4022229/DevSpacesRemoteContainer.zip)

**Comment by amsoedal** [comment]
Hi @drivexcite , 
Thanks for bringing this to our attention! Unfortunately as a dotnet core 2 app, we can't immediately support this scenario.  However we're currently pushing to migrate over to dotnet core 3 and I have logged a bug on the team to investigate this issue once we do so.

**Comment by drivexcite** [comment]
Hey @amsoedal, what do you mean you can't support this scenario in dotnetcore app 2? It works in .NET Core 2.2. It's .NET Core 3.0 and 3.1 base images where the azds command line tool is not working.

**Comment by DrEsteban** [comment]
Hey @drivexcite,

The root of this problem is around .NET Core's platform dependencies on Linux.  The azds CLI is currently built against .NET Core 2.1, which has a dependency on libssl1.0.  .NET Core 3.0 and above has revved this dependency to libssl1.1, which contains breaking API changes for any application built against libssl1.0.  This is why our CLI works against the .NET Core 2.2 base image - libssl1.0 is available there but only libssl1.1 is available in the .NET Core 3.0 base images.  Worse still, it looks like Debian 10 (the OS in the .NET Core 3.0 base images), doesn't allow you to download libssl1.0 from their package repositories by default.

After doing some poking around, though, I think I may have found a workaround.  If you follow your repro steps from above, but before running the azds command:
```bash
echo "deb http://deb.debian.org/debian jessie main" >> /etc/apt/sources.list
apt update
apt install libssl1.0.0 -y
azds prep --public
```
^ This worked for me.  It basically adds the package repository for an _older_ version of Debian which still contains the libssl1.0 package.

We have plans to update our CLI to target .NET Core 3.1, but no firm ETA yet.  Unfortunately these issues are growing pains w.r.t. .NET Core and Linux distros :(

Please let us know if that helped get you past your issue!

**Comment by drivexcite** [comment]
@DrEsteban The explanation totally helped. Thanks for taking the time to look into it.

**Comment by sebastianspross** [comment]
@drivexcite Have you a working solution? I am struggling heavily with the remote-container plugin since there is'nt such a huge community which already asked the important questions. But here is my setup which is working. I just leave my complete devcontainer.json and Dockerfile and did not cleaned it.

I basically copied some of the templates together and actually took your code to install azds. In this docker you have support for:

- node
- yarn
- docker
- K8s (and a link to the local kubeconfig)
- helm3
- azds

I definitely struggled with the ports. But after I just added any port (`80,51624,9229,37801`) I found in the `launch.json` and `tasks.json` it is working.


[devcontainer.zip](https://github.com/Azure/dev-spaces/files/4293569/devcontainer.zip)
