### ISSUE TITLE
Cannot debug non-trivial .NET Core solution with Visual Studio Code extension

### ISSUE THREAD

**Issue by acrees** [Azure/dev-spaces#269]
**Describe the bug**
I am able to debug a simple .NET core application, created with `dotnet new web`, however debugging does not start successfully for a more complex solution structure.
Since the tooling cannot automatically generate all the relevant configuration files for the solution, I have copied missing files from a working example and manually updated everything. I did manage to get something working with this strategy ~6months ago, but I'm not having any luck now. I wouldn't be surprised if I've missed something and there's a value in a file that's not quite right, but I can't see any significant differences between them, I'm pretty sure the prelauch task that's failing is exactly the same.
Running `azds up` manually, without the flags used for the persistent debugging connection, works just fine for both applications.
 
**To Reproduce**
 * Clone the repo at https://github.com/acrees/azds-issue-repo
 * Open in VS Code
 * Attempt to start debugging with the '.NET Core Launch (AZDS)' task

This causes a popup stating "The preLaunchTask azds: prelaunch' terminated with exit code 1.". The terminal shows:

```
> Executing task: C:\Program Files\Microsoft SDKs\Azure\Azure Dev Spaces CLI\azds.exe up --await-exec --keep-alive <

Could not locate an applicable session to keep ports and file synchronization alive. If calling from a tool with built-in support for Azure Dev Spaces, restart the tool.
The terminal process terminated with exit code: 1
```

I've attempted restarting VS Code and my entire machine several times, and uninstalling and reinstalling everything: the extension, cli and AZDS controller and nothing has caused any change in behaviour.
 
**Logs**
[azds-cli-2020-01-24-16-53-26-3868.txt](https://github.com/Azure/dev-spaces/files/4109691/azds-cli-2020-01-24-16-53-26-3868.txt)
[azds-sdk-2020-01-24-16-53-26-3868.txt](https://github.com/Azure/dev-spaces/files/4109692/azds-sdk-2020-01-24-16-53-26-3868.txt)
 
**Environment Details**
AZDS CLI version: 1.0.20200116.7
AZDS API version: 3.2
VS Code extension version: 2.0.220200113
Operating System: Windows 10 build 17763

**Comment by daniv-msft** [comment]
Hi Alexander,

Thank you for logging this issue, and sorry you encountered it.

From what you describe, it looks like the Azure Dev Spaces VS Code extension had troubles initializing properly.
In this context, the "applicable session to keep ports and file synchronization alive" mentioned in the error is our VS Code extension.

The first thing to do is to determine if VS Code itself logged a console error when trying to instantiate our extension:
- Close VS Code and reopen it on the repo your cloned.
- In VS Code's toolbar menu, click `Help` > `Toggle Developer Tools`. This will open a new window in VS Code.
- In this new window, open the `Console` pane from the top menu.

Could you please let me know if you see any errors in the console?
The error might not necessarily be coming from our Azure Dev Spaces extension: if one of the other extensions we have a dependency on failed to initialize, this will also prevent us from initializing properly.

Thanks!

**Comment by acrees** [comment]
There are a few messages in the console, but no errors:

```
console.ts:137 [Extension Host] You registered cluster type aks
console.ts:137 [Extension Host] You registered cluster type acs
console.ts:137 [Extension Host] You registered cluster type minikube
log.ts:190  WARN UNRESPONSIVE extension host, 'ms-kubernetes-tools.vscode-aks-tools' took 97% of 1134.028ms, saved PROFILE here: 'C:\Users\AlexR\AppData\Local\Temp\exthost-0129fc.cpuprofile' Array(6)
extensionHost.ts:203 Extension Host
extensionHost.ts:204 C:\Program Files\Docker\Docker\Resources\bin\kubectl.exe
C:\bin\kubectl.exe
Extension Host
extensionHost.ts:204 Kubernetes master is running at <url>healthmodel-replicaset-service is running at <url>CoreDNS is running at <url>kubernetes-dashboard is running at <url>Metrics-server is running at <url>
```

My full kubectl config file is also listed in the console, several times.

However, I don't believe any of this is relevant - the same warning and other messages are present when I open a sample application that does successfully start debugging in dev spaces.

**Comment by daniv-msft** [comment]
Thanks for your reply. It looks indeed like the extension was activated properly.
If it is the case, then it should have logged something in the extension's logs explaining why it couldn't initialize properly and start the handler required for debugging.

Could you please:
* Reproduce the issue in VS Code.
* Open the folder `%UserProfile%\AppData\Roaming\Code\logs\`.
* Inside the logs folder, you'll find multiple folders with names similar to `20200124T192448`. Open the one that was modified last.
* Inside this folder, you'll find multiple folders. Open the one starting with `exthost`, and that was modified last. Warning: the `exthost` folder with the highest suffix number might not be the one last modified.
* Inside this folder, you should find an `azuredevspaces.azds` folder. Overall, the path should look like `C:\Users\alias\AppData\Roaming\Code\logs\20200124T191142\exthost3\azuredevspaces.azds`.

This `azuredevspaces.azds` folder contains our VS Code extension logs.
Could you please share these logs with us, so that we can investigate further?

These logs might contain some local information about your machine (like your Windows username). Feel free to remove/obfuscate these before sending the logs.

Thanks!

**Comment by acrees** [comment]
There's only a single file in that directory, the contents of which are:

```
2020-01-28T14:04:35.515Z | Common Extension Root    | TRACE | Event: activation <json>{"workspacesCommonId":"63f35a2e-c657-7cb2-edb3-40e923827341","workspaceFoldersCount":"1"}</json>
2020-01-28T14:04:35.517Z | Common Extension Root    | TRACE | Extension activated successfully
2020-01-28T14:04:37.782Z | Common Extension Root    | TRACE | Event: azds-cli-client-get-cli-version-success
2020-01-28T14:04:37.782Z | Common Extension Root    | TRACE | Trying to initialize the workspace folder azds-issue-repo
2020-01-28T14:04:37.783Z | Common Extension Root    | TRACE | Initialization started on azds-issue-repo
2020-01-28T14:04:37.794Z | Common Extension Root    | WARNG | Initialization canceled on azds-issue-repo: unknown language
```

**Comment by daniv-msft** [comment]
We're getting closer! Thanks for sharing the logs.
This means that for some reason, our VS Code extension couldn't detect that your workspace corresponds to a .NET Core project.
Could you please validate that the .csproj file is present right inside the azds-issue-repo folder?

Unfortunately, we won't be able to detect the .csproj if it is present deeper in the folders hierarchy.

**Comment by acrees** [comment]
No, as shown in the repository I linked earlier that demonstrates this issue, I'm following the common .NET practice of having a sln file at the root of the repository, and a number of csproj projects in their own directories.

Is this not supported at all? In my experience, almost every .NET application will have at least two projects, one for application code and one for unit tests, but generally even more is common: domain modelling, data access, plugins, etc.

I was really happy with dev spaces when I used it in preview, and the developer experience it gave was a big selling point of our move to AKS. However, I can't justify the time it would take to rewrite every single application we have to this very restictive structure, just for one tool. I'm sure that's true of a great number of teams with existing projects that might consider AKS & dev spaces.

**Comment by daniv-msft** [comment]
As of today, the easiest way to make solutions work with our VS Code extension is to open its projects as a workspace in Visual Studio Code. That way, it is possible to work with Dev Spaces in a similar way as what we would have with a solution.

In your case, if you open the "web" folder in VS Code, you can generate the Dev Spaces files for it (command: "Azure Dev Spaces: Prepare configuration files for Dev Spaces") and debug it.
Then, you can add any other .NET Core project to this workspace by selecting "File" > "Add Folder to Workspace..." and use it as well with Dev Spaces.

Please note though that as of today, it is not possible to prepare Dev Spaces configuration files for .NET Standard projects (I saw that's what you used for your "domain" project).

**Comment by clintsinger** [comment]
@dakanev-msft Some more guidance on this would be helpful with respect to how to set things up using vs code workspaces.   Admittedly, from what I can find the vscodes workspace documentation is lacking.

I too am trying to figure out how to best organize my project taking into account that I have a number of projects which have dependencies on other projects and also have dependencies on a number of proto files that are up the file hierarchy that aren't in a project but are being linked in with the proto compiler.  

I am not sure how to organize everything so that the dockerfiles will build for azds, Visual Studio opens my solution fine and and currently I am able to deploy to docker desktop but am now working on getting it to kubernetes.

Also, it would be great to have some clarity how one deploys multiple projects because the documentation seems to indicate that you should do that one by one, which would be tedious with more than than the two services that the azds example shows.  There is a one-liner stating that deployment for multiple projects is done the same was as production.  My production helm chart currently uses dockerfiles from ACR, which doesn't seem right for Dev Spaces.

**Comment by daniv-msft** [comment]
@clintsinger Yes, as you saw in the BikeSharingApp, by default we expect each microservice project to be in a specific folder. You can bypass this by updating the files we generate to match your solution's structure (cf. comments in a previous issue: https://github.com/Azure/dev-spaces/issues/120#issuecomment-518413765 and https://github.com/Azure/dev-spaces/issues/120#issuecomment-513506747).

That said, I also logged a work item on our side to document this and determine if we can do any better here. I'll update this issue once we release this documentation.

**Comment by daniv-msft** [comment]
@clintsinger We added a new entry into our documentation about this: https://docs.microsoft.com/en-us/azure/dev-spaces/faq#can-i-use-azure-dev-spaces-with-multiple-microservices-in-an-application

That said, more work is needed on our side to provide a better experience in VS Code. As of today, Visual Studio is able to prepare .NET Core solutions for Dev Spaces (thus taking into account projects dependencies), but VS Code isn't.
Because VS Code doesn't have this concept of solutions, we need to determine how to make this work with the workspace paradigm.

In the meantime, if you're able to deploy your solution from Visual Studio, you should be able to make it work in VS Code as well by reusing the files (Dockerfile, Dockerfile.develop, etc.) created for you by Visual Studio when preparing it for Dev Spaces.

Specifically, you should only have to:
* Open the startup project in VS Code.
* Validate that it contains the Dev Spaces required files (azds.yaml, Dockerfile, Dockerfile.develop, etc.) created by Visual Studio.
* Make sure that the files were generated by Visual Studio for the whole solution and not only for this project. An easy way to check this is to look at the Dockerfile and check if all dependencies are copied, and not only this project (`COPY ["OtherLibrary/OtherLibrary.csproj", "OtherLibrary/"]`).
* Make sure that you have the Dev Spaces launch configuration in your launch.json (named `.NET Core Launch (AZDS)`).
* Update the launch configuration to match your solution's files architecture. In my case, I only had to update the `cwd` and `program` fields so that they contained the name of the startup project:
```
{
    ...
    "cwd": "/src/NAME_OF_THE_STARTUP_PROJECT/",
    "program": "/src/NAME_OF_THE_STARTUP_PROJECT/bin/Debug/netcoreapp3.1/NAME_OF_THE_STARTUP_PROJECT.dll",
    "sourceFileMap": {
        "/src": "${workspaceFolder}/.."
    }
}
```
* Open other dependencies project as a workspace in VS Code.
* Debug using the Dev Spaces launch configuration.

I'll try to create a sample solution and push it on GitHub next week so that you can see a live example.
