### ISSUE TITLE
[java] Error when trying to run 'Azure Dev Spaces: Prepare Configuration files for Azure Dev Spaces' it complains about missing Maven

### ISSUE THREAD

**Issue by dan-alford** [Azure/dev-spaces#353]
When trying to configure a project for Azure Dev Spaces/Java, When I run Azure Dev Spaces: Prepare Configuration files for Azure Dev Spaces it gives the following error

Failed to validate the Azure Dev Spaces Debug configuration in launch.json for <project> Error: Maven is required, please download and install Maven at https://maven.apache.org/download.cgi.

Envrionment:
macOS Catalina - 10.15.3
Visual Studio Code

Maven was originally installed via homebrew and paths configured. I downloaded maven binary and tried that with paths and still seeing the issue.

Note: This is for a project that had an existing docker file. The extension created a Dockerfile.develop file

**Comment by daniv-msft** [comment]
Thank you for reporting this issue, and sorry you encounter it.

For context, do you have other Java apps working with Azure Dev Spaces, or is this the only one?
From what you describe, I expect this issue to be independent from the current app.

I'm also wondering if this could be due to VS Code not reading properly the PATH from environment variables.
* Could you confirm that, in a command prompt, you can run `mvn` or `mvnw`?
* If you can find the Maven command properly, could you try to close all VS Code instances, open VS Code from this command prompt (`code`) and try to reproduce the issue?
