### ISSUE TITLE
Question: Tunneling MsSql to local migration?

### ISSUE THREAD

**Issue by TonyMoonStar** [Azure/dev-spaces#385]
Hi,

We are planning to move fully to AKS with use of Dev Space and would consider also moving Sql DB to AKS.
During our discussions, we came to none clear answer about Sql DB on Dev Space regarding to Tunneling.

So we are using EF with Migrations, is it possible to configure Dev Space to have isolated Sql changes on specific namespace during Dev Space run?

**Comment by daniv-msft** [comment]
Hi @TonyMoonStar,
Thank you for opening this issue.

Rather than moving to Dev Spaces, please consider using Local Process with Kubernetes instead, that is a simpler solution to many of the development scenarios that Dev Spaces currently fulfils and is where we invest our engineering efforts.
You can learn more here:
* [How Local Process with Kubernetes Works](https://docs.microsoft.com/en-us/azure/dev-spaces/how-dev-spaces-works-local-process-kubernetes)
* [How to use Local Process with Kubernetes in Visual Studio 2019](https://aka.ms/localprocesswithk8s-vs)
* [How to use Local Process with Kubernetes in Visual Studio Code](https://aka.ms/localprocesswithk8s-vsc)

Regarding having an isolated database in a specific namespace, this is not something that will be handled by default (neither by Dev Spaces or by Local Process with Kubernetes).

Because Dev Spaces and Local Process with Kubernetes are development tools, they are used on development clusters which often have a specific test/development DB.
In your case, you would need to deploy such specific version of your database manually and redirect the calls in your service calling it, based on the value of the HTTP header we use when routing traffic (`kubernetes-route-as` for Local Process with Kubernetes, `azds-route-as` for Dev Spaces).

**Comment by lKoTl** [comment]
Thanks @daniv-msft ,
This is where were leaning with our internal discussion. Seems we understood it correctly, just wanted to double check.

Thanks again for the clarification.
