### ISSUE TITLE
Feature : Add a command for updating the controller

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#388]
There is no intuitive way to update the controller to a new build today.

Maby add a new command to the azds tool?

`azds controller update`

The "update" command should reuse the old HostSuffix

(What is the easiest way to update the controller today?)

**Comment by philon-msft** [comment]
Hi @Eneuman, we automatically update all Controllers whenever we release a new build of the Dev Spaces services, so it shouldn't be necessary to manually update. However there are a couple of catches: 
- If during the update, you have services running that were launched with 'azds up', you'll need to 'down' those and re-up them to pick up the new bits for that service.
- If you have a really old Controller based on Helm 2, you'll want to "update" it by deleting it and creating a new Controller for that cluster (the new one will use Helm 3). 

Are you seeing an issue where new bits aren't getting picked up as expected?

**Comment by Eneuman** [comment]
Hi @philon-msft 

I think my controller is kinda old. Im receiving this message when each time we start debugging.

****NOTE: A new version of the Azure Dev Spaces Controller using Helm 3 is now available. Consider recreating your Azure Dev Spaces Controller to get the upgraded version. Any Azure Dev Spaces Controllers not upgraded by September 1, 2020 will be automatically upgraded, which may cause disruption to running services.****

If I do a "azds down" and "azds up", it will also recreate the controller?
Will the hostsuffix (for my public ingress) for the service change if I do this?

**Comment by philon-msft** [comment]
Hi @Eneuman, that Controller is indeed pretty old. The only way to upgrade it is to remove it and create a new Controller for the cluster. The easiest way is with a couple CLI commands:
`azds remove -n [clusterName] -g [resourceGroupName]`
`az aks use-dev-spaces -n [clusterName] -g [resourceGroupName]`

It's also a good idea to `azds down` services before removing the Controller, and then `azds up` them with the new Controller. 

The hostsuffix for the recreated Controller will be different from what it is now.

I know you're familiar with LPK, but for anyone else reading this issue: we're strongly recommending that people move from Dev Spaces Controllers to the new LPK tools (#341). If you have an old Controller, this is a great opportunity to [check out LPK](https://github.com/Azure/dev-spaces/issues/341) instead of recreating the Controller. If LPK isn't a viable replacement for Dev Spaces in your case, we'd love to hear more about your scenario so please let us know.

**Comment by Eneuman** [comment]
Hi @philon-msft 
We are interested in moving to LPK but at the moment some key elements are missing. 

We rely heavily on Managed Identity and Pod Identity and from what I have been told there is no easy way around this today. Most services are also using Azure Service Bus with topics (all communication is event driven with eventual consistency) and I don't think this is supported in LPK :(

But we are eagerly waiting for this functionality so we can try it out.
