### ISSUE TITLE
failed to list dev space.

### ISSUE THREAD

**Issue by RyanHuynh** [Azure/dev-spaces#392]
Hi I'm fairly new to Azure Dev Space. I'm doing a POC for my company to use Azure Dev Space with our Dev Ops. I'm following some tutorial to setup Azure Dev Space for my AKS. It looks like the controller is created without problem but I can't seem to select the controller or dev space at all.
Here is attached logs that I found. Hope someone can point me to direction to resolve this issue.
[azds-cli-2020-08-25-04-58-01-7356.txt](https://github.com/Azure/dev-spaces/files/5121420/azds-cli-2020-08-25-04-58-01-7356.txt)
[azds-sdk-2020-08-25-04-58-01-7356.txt](https://github.com/Azure/dev-spaces/files/5121421/azds-sdk-2020-08-25-04-58-01-7356.txt)

**Comment by sanar-microsoft** [comment]
@RyanHuynh Looks like an authentication issue when talking to the AKS cluster's API server. Can you try replacing cluster context in your default kubeconfig for cluster `AKSWESTUS` with the admin credentials? You can get them by running:
`az aks get-credentials -a -n <name> -g <resource group>`

**Comment by daniv-msft** [comment]
@RyanHuynh Also, something important to mention is that we would strongly suggest that you have a look at Local Process with Kubernetes rather than starting integrating with Azure Dev Spaces.
Local Process with Kubernetes provides a better experience compared to Azure Dev Spaces, and this is where our engineering efforts are invested now.

Here are good places to start:
[How Local Process with Kubernetes Works](https://docs.microsoft.com/en-us/azure/dev-spaces/how-dev-spaces-works-local-process-kubernetes)
[How to use Local Process with Kubernetes in Visual Studio 2019](https://aka.ms/localprocesswithk8s-vs)
[How to use Local Process with Kubernetes in Visual Studio Code](https://aka.ms/localprocesswithk8s-vsc)
