### ISSUE TITLE
EndpointManager launch process fail

### ISSUE THREAD

**Issue by ghostcoach** [Azure/dev-spaces#418]
When migrating to Bridge to kubernetes from Dev Spaces the elevation process fails for me. After accepting the elevated privileges I get the error "The EndpointManager launch process has exited". As far as I can see no logs (logs are enabled) for bridge to kubernetes are produced in my Temp folder. 

Do I need to configure my client in any additional way to support endpoint manager? 

![bild](https://user-images.githubusercontent.com/63369949/102637381-32310b80-4156-11eb-876c-1a39749e0d56.png)
![bild](https://user-images.githubusercontent.com/63369949/102635809-1dec0f00-4154-11eb-89c0-a1eccdec0e08.png)

I am running Visual Studio as an administrator. 

Visual Studio Version: 16.8.3
Bridge to kubernete extension version: 2.0.20201216.1

Kubernetes version: 
Client: 1.19.3
Server: 1.19.3

**Comment by daniv-msft** [comment]
Thank you for logging this issue and sorry you encounter it.
This looks like a bug on our side, and we would need more logs to investigate further.

Could you please provide the latest logs present in `%TEMP%/Bridge to Kubernetes`?
I'm especially interested by the latest `bridge-endpointmanager-*` and the `bridge-library-*` logs that should contain more information.
These logs might contain personally identifiable information, so if you don't feel comfortable attaching them to this GitHub issue, please don't hesitate to send them by email directly to `BridgeToKubernetes@microsoft.com`.

Also, I see that we're trying to stop the World Wide Web Publishing Service in your case. In the past, we encountered an issue related to this (https://github.com/Azure/dev-spaces/issues/401). This issue was now fixed for a long time, but in case we had a regression, could you please try to stop this service manually (from the `Services` app on Windows) and retry Bridge?

**Comment by ghostcoach** [comment]
Thanks for your reply. I stopped World Wide Web Publishing Service manually with the result that VS no longer tries to stop it. Unfortunately, the problem still persist.

I am attaching the logs from my latest try. 

[bridge-library-2020-12-19-00-47-02-30860.txt](https://github.com/Azure/dev-spaces/files/5718677/bridge-library-2020-12-19-00-47-02-30860.txt)
[bridge-mindarocli-2020-12-19-00-46-42-30396.txt](https://github.com/Azure/dev-spaces/files/5718678/bridge-mindarocli-2020-12-19-00-46-42-30396.txt)
[bridge-mindarocli-2020-12-19-00-47-02-30860.txt](https://github.com/Azure/dev-spaces/files/5718679/bridge-mindarocli-2020-12-19-00-47-02-30860.txt)
[bridge-endpointmanager-2020-12-19-00-47-05-21040.txt](https://github.com/Azure/dev-spaces/files/5718680/bridge-endpointmanager-2020-12-19-00-47-05-21040.txt)
[bridge-library-2020-12-19-00-46-42-30396.txt](https://github.com/Azure/dev-spaces/files/5718681/bridge-library-2020-12-19-00-46-42-30396.txt)

**Comment by daniv-msft** [comment]
Thanks @ghostcoach for your reply and sharing these logs.
I confirm we get an exception when starting the EndpointManager. The exception happens when we instantiate a `new System.Net.Sockets.Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.Unspecified)` and we get a SocketException: `An address incompatible with the requested protocol was used.`.
Please note that even though we're mentioning a Unix socket here, this code will work on Windows as .NET Core support Unix Domain Sockets.

We need to investigate this issue further and will get back to you once we understand better what's happening.
Adding @amsoedal for FYI.

**Comment by amsoedal** [comment]
Hi @ghostcoach, thanks for reporting this issue!  I'm not able to repro this issue myself, but I'm wondering if it could be due to any socket or IP configurations on your side.  Would you be open to trying a winsock reset as described [here](https://www.lifewire.com/netsh-winsock-reset-4684099)?  If that doesn't fix it, my second guess would be to try running `ipconfig /release && ipconfig /renew`.  Let me know how it works for you!

**Comment by ghostcoach** [comment]
Thanks for taking the time @amsoedal to try to reproduce my issue. Winsock reset or ipconfig did not solve the issue. 

In order to try a more clean scenario I reinstalled Windows on my client and reinstalled all programs and sdks. Then I followed [this guide](https://docs.microsoft.com/sv-se/visualstudio/containers/bridge-to-kubernetes?view=vs-2019) so I could try with a new service in a new k8s-cluster. I also turned off Windows Firewall. Unfortunately I still get the error about Endpoint manager.

Is there any other configuration or setting for my client I can look at?

Visual Studio: 16.8.3
Bridge to Kubernetes Extension: 2.0.20201216.1
Azure CLI: 2.16.0

[bridge-endpointmanager-2020-12-28-08-13-50-135220.txt](https://github.com/Azure/dev-spaces/files/5746391/bridge-endpointmanager-2020-12-28-08-13-50-135220.txt)
[bridge-library-2020-12-28-08-13-43-134716.txt](https://github.com/Azure/dev-spaces/files/5746392/bridge-library-2020-12-28-08-13-43-134716.txt)
[bridge-mindarocli-2020-12-28-08-13-43-134716.txt](https://github.com/Azure/dev-spaces/files/5746393/bridge-mindarocli-2020-12-28-08-13-43-134716.txt)
[bridge-library-2020-12-28-08-13-48-133992.txt](https://github.com/Azure/dev-spaces/files/5746394/bridge-library-2020-12-28-08-13-48-133992.txt)
[bridge-mindarocli-2020-12-28-08-13-47-133992.txt](https://github.com/Azure/dev-spaces/files/5746395/bridge-mindarocli-2020-12-28-08-13-47-133992.txt)

**Comment by amsoedal** [comment]
Hi @ghostcoach, thanks for giving that a try & sorry it didn't unblock you! Can you tell me more about your system -- when you say you reinstalled Windows on your client, are you running a VM? What OS version are you running?

**Comment by ghostcoach** [comment]
@amsoedal, when I say reinstalled Windows I mean reinstalled my computer.  My system information are:

![image](https://user-images.githubusercontent.com/63369949/103228098-4af8a880-4930-11eb-951e-8b48fc570445.png)

**Comment by amsoedal** [comment]
Thanks for providing those details @ghostcoach! I've reached out to the dotnetcore team to see if they can help as well, although I'm expecting a delayed response due to the holidays. I'll try to keep this thread updated as soon as I hear back from them.

**Comment by amsoedal** [comment]
Thanks for the patience @ghostcoach. It turns out the Unix Domain Sockets we're using for IPC are only supported on Windows 10 version 1803 (10.0.17134) and onwards. I believe upgrading your Windows version should fix the issue!

**Comment by ghostcoach** [comment]
I can happily confirm @amsoedal that updating Windows 10 to a newer version solved to problem for me! 
Thanks a lot for your troubleshooting and the coordination with the dotnetcore team. This really makes a difference for me and my development team.

**Comment by amsoedal** [comment]
I'm happy to hear it!
