### ISSUE TITLE
Error while add Kubernetes support to an existing ASP.NET web application project

### ISSUE THREAD

**Issue by knoxi** [Azure/dev-spaces#53]
I get an error when I try to add Kubernetes support to an existing ASP.NET web application project:

![image](https://user-images.githubusercontent.com/5229316/51844025-92c1c000-2314-11e9-8762-47e2fee52c2a.png)

I have no more information about what is going wrong.

**Comment by lisaguthrie** [comment]
@knoxi - can you enable detailed logging for the Visual Studio extension: https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting#enabling-detailed-logging

And then try to repro and let us know what you see in the logs? Thanks!

**Comment by knoxi** [comment]
I enabled detailed logging by setting the environment variable `MS_VS_AZUREDEVSPACES_TOOLS_LOGGING_ENABLED`, but there is no folder created in `%TEMP%\Microsoft.VisualStudio.Azure.DevSpaces.Tools`.
There is a folder `%TEMP%\Azure Dev Spaces` but only with empty files.

**Comment by lisaguthrie** [comment]
Did you restart VS after enabling logging? Is the folder still not created after you repro?

**Comment by knoxi** [comment]
Yes, I restarted VS several times, but the folder is not created.
Also the newest extension update form today doesn't helped.

**Comment by mthalman** [comment]
@knoxi - Does the project on which you're attempting to add Kubernetes support exist outside the solution's directory?  If so, that's the problem.  It needs to be somewhere inside the solution's directory so that we're able to create a Docker build context at the solution-level.

If that's not the problem, then you'll need to attach another instance of VS as a debugger so that you can catch the exception that's getting thrown.  It'll provide the underlying error information.  To do that, start with your VS instance that you want to repro the issue with and get to the point where you're at the Add Orchestration Support dialog.  Then attach another instance of VS to your first instance of VS and configure it to break on all CLR exceptions.  Then go ahead and confirm the Add Orchestration Support dialog until you get the error.  It should break on the exception that's being thrown and provide more detailed info.

We have better diagnostic information for handling these types of errors in VS 2019.

**Comment by knoxi** [comment]
@mthalman - The project on which I'm attempting to add K8 support is inside the solution, but there is also a shared common project within the solution which is outside the solution folder:

Solution: `C:\Repos\Services\Management\`
ASP.Net : `C:\Repos\Services\Management\WebApp\WebApp.csproj`
Common lib: `C:\Repos\Services\Common\Common.Security\Common.Security.csproj`

**Comment by mthalman** [comment]
@knoxi -  If you have a shared common project outside the solution folder, that configuration will also not work.  The build context defines the scope of the set of files that will be copied to the Docker daemon in order to build the Docker image.  In this case, the build context will be the solution folder.  If you have referenced files that are outside the solution folder, they will not be copied to the Docker daemon and the solution build will fail.  All files referenced by an orchestrated project must be in the scope of the solution folder.

**Comment by knoxi** [comment]
@mthalman - ok, I thought, only the affected web app project should be inside the solution folder.
I will create an overlying solution including all projects folders and test it again.

**Comment by YuzorMa** [comment]
@knoxi Were you able to get this to work with the instructions @mthalman provided?

**Comment by knoxi** [comment]
Yes, I was able to handle it with these instructions.
