### ISSUE TITLE
azds.yaml - container sync

### ISSUE THREAD

**Issue by MrMcGibblets** [Azure/dev-spaces#73]
I have a node app that lives underneath the .net core app directory. Currently, this isn't published or synced to the container within dev-spaces. I have updated the azds.yaml file sync object to include this folder, but that doesn't have any effect, is there more to it than just adding it here?

**Comment by MrMcGibblets** [comment]
There is a useGitIgnore property which I think it might use to determine the files to sync, when i turn this to false i get:

> There is no more space available for file synchronization. Please remove unused spaces by running 'azds down', reduce the size of your workspace, and retry later.

If someone can confirm that would be great and if so any advice on my options as i dont want to commit this to source as it is built dynamically.

**Comment by xinyanmsft** [comment]
Hi, Andrew,
The 'no more space available' error is probably because the node_modules directory has too many files and exhausted the space allocated.
I suggest you do this:
1. Is your packages.json and *.js files checked in as sources? If not (and they are excluded by .gitIgnore file), set 'useGitIgnore' to false, and create/update your '.dockerIgnore' file. In your .dockerIgnore file, please exclude what you've excluded via '.gitIgnore' in terms of /bin/ and /obj folders, and also exclude node_modules folder as well. 
    If your packages.json and *.js files are checked in as source, that's Okay. your .gitignore file should already filter node_modules directory. But from your description it seems this is not the case.

2. You need to add equvilent of 'npm install' steps to your Dockerfile / Dockerfile.develop.

**Comment by MrMcGibblets** [comment]
Hi, 

Thanks for your reply.

the package.json and js source files are checked in, however, the build of these are not. What you have pointed me to is that I wasn't building these in the container and therefore they would never exist. 

The dockerfile now runs npm install and npm run-script build successfully however when loading it fails with:

> failed to watch file "" no space left on device

I imagine similar reasons to above but obviously, I need the node_modules folder all running in the container for the app to work.

**Comment by xinyanmsft** [comment]
Hi, Andrew,

The 'failed to watch file' issue probably should be a separate issue. I've seen them sporadically, because the Kubernetes cluster node ran out of watcher objects. In Azure Kubernetes Services, by default the user watcher object limit is set to 8192, which is quite low (https://github.com/Azure/AKS/issues/772). 
You can use the attached yaml file to increase the watcher object limit on your cluster:

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: more-fs-watchers
  namespace: kube-system
  labels:
    app: more-fs-watchers
spec:
  template:
    metadata:
      labels:
        name: more-fs-watchers
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      initContainers:
        - command:
            - sh
            - -c
            - sysctl -w fs.inotify.max_user_watches=524288;
          image: alpine:3.6
          imagePullPolicy: IfNotPresent
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys
              mountPath: /sys
      containers:
        - resources:
            requests:
              cpu: 0.01
          image: alpine:3.6
          name: sleepforever
          command: ["tail"]
          args: ["-f", "/dev/null"]
      volumes:
        - name: sys
          hostPath:
            path: /sys

And remember to restart the cluster nodes afterwards.

thanks!

Xin

**Comment by MrMcGibblets** [comment]
Thanks for your help Xin, that did fix my issue. The original issue regarding syncing I am still struggling with.

My dockerfile now runs my NPM build which builds my js files and places them in a dist folder which is included in the .gitignore file

I have set the useGitIgnore flag to false (updated my dockerignore) and ran azds up, I included the top level folder where the dist folder lives to sync object in the azds.yaml file. However, it still doesn't sync files that are set in the gitignore. I am certain it is a local issue, but can't seem to track down what it could be.

**Comment by xinyanmsft** [comment]
Hi, Andrew,
Is it possible you send me a sample project / dockerfile / ignore files / azds.yaml illustrate your scenario?
thanks
Xin

**Comment by MrMcGibblets** [comment]
[azds.zip](https://github.com/Azure/dev-spaces/files/3016741/azds.zip)
 Attached is the dockerfile.develop, AZDS.yaml and .dockerignore

**Comment by xinyanmsft** [comment]
Here's a sample about having a node js app and a C# app in the same container. However I should say if you have two web sites, the best way is to have them in separate projects.
I guess the problem you have is around your Dockerfile which doesn't seem to copy the js files.
[sample.zip](https://github.com/Azure/dev-spaces/files/3020190/sample.zip)

**Comment by MrMcGibblets** [comment]
Thanks
