### ISSUE TITLE
Dev spaces with Linkerd - Pods stuck on initalizing

### ISSUE THREAD

**Issue by da1rren** [Azure/dev-spaces#78]
Hey Guys,

I'm having some trouble using dev spaces with a linkerd enabled kubernetes cluster.  Linkerd is set to auto-inject into any deployments created in a particular namespace.  But it seems that when using azds up the deploy hangs and pods get stuck initalizing.

I've deploy other containers to the namespace successfully.  Any ideas?

Heres the deployment:
```
Name:                   webapplication1
Namespace:              darren
CreationTimestamp:      Fri, 05 Apr 2019 13:36:54 +0100
Labels:                 app=webapplication1
                        chart=webapplication1-0.1.0
                        draft=draft-app
                        heritage=Tiller
                        linkerd.io/control-plane-ns=linkerd
                        linkerd.io/proxy-deployment=webapplication1
                        release=azds-842081-darren-webapplication1
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=webapplication1,release=azds-842081-darren-webapplication1
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=webapplication1
                draft=draft-app
                linkerd.io/control-plane-ns=linkerd
                linkerd.io/proxy-deployment=webapplication1
                release=azds-842081-darren-webapplication1
  Annotations:  buildID=
                linkerd.io/created-by=linkerd/proxy-injector stable-2.2.1
                linkerd.io/proxy-version=stable-2.2.1
  Init Containers:
   linkerd-init:
    Image:      gcr.io/linkerd-io/proxy-init:stable-2.2.1
    Port:       <none>
    Host Port:  <none>
    Args:
      --incoming-proxy-port
      4143
      --outgoing-proxy-port
      4140
      --proxy-uid
      2102
      --inbound-ports-to-ignore
      4190,4191
    Environment:  <none>
    Mounts:       <none>
  Containers:
   webapplication1:
    Image:        webapplication1:devspaces-x0169ed8076cfdb63
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
   linkerd-proxy:
    Image:       gcr.io/linkerd-io/proxy:stable-2.2.1
    Ports:       4143/TCP, 4191/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get http://:4191/metrics delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:   http-get http://:4191/metrics delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      LINKERD2_PROXY_LOG:                           warn,linkerd2_proxy=info
      LINKERD2_PROXY_CONTROL_URL:                   tcp://linkerd-proxy-api.linkerd.svc.cluster.local:8086
      LINKERD2_PROXY_CONTROL_LISTENER:              tcp://0.0.0.0:4190
      LINKERD2_PROXY_METRICS_LISTENER:              tcp://0.0.0.0:4191
      LINKERD2_PROXY_OUTBOUND_LISTENER:             tcp://127.0.0.1:4140
      LINKERD2_PROXY_INBOUND_LISTENER:              tcp://0.0.0.0:4143
      LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES:  .
      LINKERD2_PROXY_POD_NAMESPACE:                  (v1:metadata.namespace)
      LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE:      10000ms
      LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE:    10000ms
      LINKERD2_PROXY_ID:                            webapplication1.deployment.darren.linkerd-managed.linkerd.svc.cluster.local
    Mounts:                                         <none>
  Volumes:                                          <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  <none>
NewReplicaSet:   webapplication1-674db99f7c (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  3m    deployment-controller  Scaled up replica set webapplication1-674db99f7c to 1
```

**Comment by stepro** [comment]
@da1rren, can you send me the description of the pod created by this deployment? In general, we know that dev spaces does not work with linkerd or istio because of conflicts with our own service-mesh-like proxy, but given the increased adoption of service meshes we're looking to enable that. Can you also describe how you installed linkerd in the cluster? Thanks!

**Comment by da1rren** [comment]
Sure thing!

The pod is extremely simple, its a single .net core 2.2 mvc app using the default dotnet new template.  The docker file is generated from the azds prep command.

The Linkerd install was also pretty straight forwards however we where making use of the [automating injection](https://linkerd.io/2/tasks/automating-injection/) feature of Linkerd.  Basically I create a namespace with an annotation and linkerd then automatically installs inself into any pods/services created with that namespace.

Does that help at all @stepro?

**Comment by stepro** [comment]
Thanks @da1rren. Can you send the output of "kubectl get pod" on the pod that's created but stuck in the waiting state? You may need to specify the "--include-uninitialized" option to find it.

**Comment by da1rren** [comment]
![image](https://user-images.githubusercontent.com/2702382/55674715-482e6800-58b0-11e9-90c1-2743beee0b77.png)

As request.  Do you require anything else @stepro ?

**Comment by wmorgan** [comment]
If there's anything we can do to ease this from the Linkerd side, please let me know. (cc @grampelberg)

**Comment by sanar-microsoft** [comment]
@da1rren Does the 'kubectl describe pod <name>' output show any problem with the second init container?

**Comment by stepro** [comment]
@da1rren I'm pretty sure this isn't going to work right now, but given the increased demand for service meshes, we do want to make sure the dev space scenarios continue to work.

@wmorgan, thanks for the reach out. My investigations into iptables, netfilter etc. show that it might be possible to make two service meshes cooperate with each other, if they know when to yield to the other. I'm on vacation this week but will follow up next week with some more specifics. This might prove to be a reasonable short term solution, but longer term we'd ideally drop our implementation in favor of configuring whatever service mesh happens to be installed.

Before we can do this, we'd need to make sure the features we currently provide are covered by the service mesh. In particular, we intercept all TCP connections and auto-detect when the bytes look like HTTP, then do a couple of specific things:
- Route to backend services in different namespaces based on an `azds-route-as` header and whether the services actively accept TCP connections;
- Trace the HTTP request/response in real time back to the developer's machine.

Our proxy requires no configuration because it's highly specialized to the above capabilities, but we have the means to configure an alternate implementation if it covers our needs. Can you comment on Linkerd's support for the above?

**Comment by grampelberg** [comment]
> Route to backend services in different namespaces based on an azds-route-as header and whether the services actively accept TCP connections;

There is a `l5d-dst-override` header that does that.

> Trace the HTTP request/response in real time back to the developer's machine.

Yup, `tap` will do it!

**Comment by stepro** [comment]
@grampelberg, this is good to know. I recognize the `l5d-dst-override` header from when I'd played with linkerd previously, so I was pretty sure this was possible. Didn't know about `tap` - is it possible to tap all the services running in a namespace simultaneously? Thanks!

**Comment by grampelberg** [comment]
Totally possible!

**Comment by aaronwjha** [comment]
What is the status on this? Is linkerd supported in AZDS?
