### ISSUE TITLE
[Request] SPA application support

### ISSUE THREAD

**Issue by eiximenis** [Azure/dev-spaces#94]
Is in the roadmap to consider the support of **SPA** applications in Devspaces?

If using `azds prep` against a SPA app, it is treated like a standard MVC/webapi webapp, but "dotnet build" in SPA apps requires nodejs which is not shipped with the netcore SDK images.

Currently workarounds i am aware of are:

1. Install nodejs in the netcore sdk image
2. Use a multistage Dockerfile.develop, and build the frontend files using a nodejs and copy the generated bundles to the final dotnet sdk image. But this don't allow the use of tools like react-web-server.

None of these are ideal solutions :)

**Comment by stepro** [comment]
In the past, the ASP .NET Core build images included node, but they have moved away from this due to problems around which version of node was needed. Your best option is to derive your own image that includes the version of node you want, or just embed the installation of node in your Dockerfile. The easiest way to get whatever node version you want is to use [n](https://github.com/tj/n) via [n-install](https://github.com/mklement0/n-install). It's up to you whether you want to install it in a way that it is available to the final running app or whether it's only for build purposes.
